version: "3.9"

services:
  node:
    image: node:18
    container_name: node_app
    working_dir: /app
    volumes:
    - ./app:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    tty: true

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    ports:
      - 4040:4040
    env_file:
      - .env
    command: ["http", "node:3000"]
    depends_on:
      - node

networks:
  default:
    name: docker_ngrok